image: python

stages:
     - build
     - test
     - deploy

     build-job:
     stage: build
     script:
          - python3 -V

    test count:
    stage: test
    script:
         - pythin3 sum.py

    deploy-job:
        stage: deploy
        script:
              - echo "terminou"
     
